apiVersion: v1
kind: Secret
metadata:
  name: boardforpeace-secrets
  namespace: boardforpeace
type: Opaque
stringData:
  app-key: "base64:II/JOZ3Sk3maWZ38pW85kuFrVDBh9fFHc82NWmBbWW8="
  db-username: "root"
  db-password: "password"
