apiVersion: v1
kind: Service
metadata:
  name: boardforpeace-reverb
  namespace: boardforpeace
  labels:
    app: boardforpeace
    tier: reverb
spec:
  selector:
    app: boardforpeace
    tier: reverb
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
